### ISSUE TITLE
EPIC: Social Upgrades

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1014]
We've discussed the desire for validators and consensus fullnodes to be able to update binaries before the actual upgrade height. This differs from the standard cosmos-sdk upgrade module, which typically relies on switching binaries at the upgrade height. 

#### Tracking
- [x] #1491 
- [x] https://github.com/celestiaorg/celestia-app/issues/1571
- [ ] ADR for social upgrades #1562 
- [ ] https://github.com/celestiaorg/celestia-app/issues/2464

**Comment by evan-forbes** [comment]
related to #1009 in that we also want to remove most text based governance proposals, which includes upgrade proposals

**Comment by evan-forbes** [comment]
After implementing auto switching upgrades, there's an interesting addition proposed by @cmwaters where we can add a signalling component. Each node would gossip when each node is ready to upgrade. Nodes can then vote to upgrade after they have received 2/3s. This would also need to be communicated with light clients, which would also need to upgrade at that time.

**Comment by MicahZoltu** [comment]
It seems like it would be trivial to Sybil attack such a signaling mechanism, and in fact I struggle to imagine a future where such a mechanism *isn't* Sybil attacked eventually.

**Comment by evan-forbes** [comment]
> It seems like it would be trivial to Sybil attack such a signaling mechanism

apologies, I wasn't clear enough, by 2/3's I mean 2/3's of the voting power of validators, not just full nodes. Would this still be subject to a sybil attack? It seems like it would be easy to check if a message was sent from from a validator and remove a peer if they're not, but I definitely could be missing something.

**Comment by MicahZoltu** [comment]
Ah, if it is 2/3 of validators (not nodes) then it isn't susceptible to Sybil.

This is still susceptible to governance attacks though.  In a well designed PoS network validators are tightly constrained on the damage they can do, usually limited to censorship and double spending within finality window.  It is important to be careful not to give validators additional powers like the ability to push out a rule change onto users (which effectively is ultimately unconstrained power).

Thinking more on this, I am somewhat against the signalling mechanism you have proposed.  Imagine if an honest minority wants to execute a fork away from a dishonest majority.  By having them wait for the signal from the validators they would be functionally blocked from forking away by the dishonest majority.

If a user has decided that they want to apply a rule chain, they should be allowed to do so freely regardless of what other network participants think/want.

**Comment by cmwaters** [comment]
>  Imagine if an honest minority wants to execute a fork away from a dishonest majority. 

No one's blocking anyone from forking. A minority simply takes the block chain, makes some updates to the validator set and starts their own alternative binary. 

A signalling mechanism is merely a coordination tool; you can't force node operators to upgrade or to not. Computers are just faster and more reliable at coordinating than if we were to try organize something on discord for example.

**Comment by MicahZoltu** [comment]
Perhaps I'm missing something, but manual updates to validator set feels fraught with peril.  For starters, the honest minority would need to know in advance which validators are honest and which are dishonest.  This information may not be known until you attempt to fork and find that some validators didn't upgrade.  Even then, you cannot differentiate between validators that intentionally didn't upgrade their clients (because they oppose the fork) and those who just weren't paying attention.  It feels disingenuous to fully slash those who were just not paying attention.

On top of that, I believe the validator set changes over time, so you would need to author a list of validators to remove, and then release quickly enough after that list was published before a substantial number of those validators can rotate out.

All in all, it feels like this sort of fork should be reserved only for the worst case scenarios like active censorship of the blockchain, and shouldn't be the way to handle contentious upgrades where the community is split on how to proceed.

**Comment by musalbas** [comment]
>This differs from the standard cosmos-sdk upgrade module, which typically relies on switching binaries at the upgrade height.

How are you typically expected to sync from genesis with this method? Do you have to run older, unsupported binaries? This seems unsustainable if older binaries have to be supported in perpetuity.

**Comment by cmwaters** [comment]
> Perhaps I'm missing something, but manual updates to validator set feels fraught with peril.

How else do you fork with only an honest minority and a dishonest majority without changing the validator set in some way.

Anyway, I think I may have confused you here. I wasn't really talking about forks, I just brought it up to say that this is an orthogonal process. It's purely to automate coordination. Instead of saying everyone needs to update at height 100. Everyone updates in their own time and then communicates to other nodes that they're ready to upgrade. When 2/3+ of the validator set have communicated their intention to upgrade, the next block proposer proposes a block with the new app version. If it gets accepted everyone then switches to the new version (this means of course that a binary will include two state machines: the old and the new).

**Comment by cmwaters** [comment]
> How are you typically expected to sync from genesis with this method? Do you have to run older, unsupported binaries? This seems unsustainable if older binaries have to be supported in perpetuity.

Yes, for example osmosis is up to v13 which means you'd start at v1 till you reached the upgrade height, swap in v2 and keep doing that until you reached the head of the chain.

Old binaries don't have to be supported in perpetuity in terms of software maintenance, they just need to exist.

**Comment by musalbas** [comment]
>Instead of saying everyone needs to update at height 100. Everyone updates in their own time and then communicates to other nodes that they're ready to upgrade.

IMO we should force an upgrade at a certain height regardless of who's ready to upgrade or not, and automatically un-delegate the validators that didn't signal. Validators should not have the power to delay or block upgrades that the community wants. See https://github.com/celestiaorg/celestia-app/issues/1009#issuecomment-1323700120 for reasoning.

**Comment by musalbas** [comment]
>Yes, for example osmosis is up to v13 which means you'd start at v1 till you reached the upgrade height, swap in v2 and keep doing that until you reached the head of the chain.
>
>Old binaries don't have to be supported in perpetuity in terms of software maintenance, they just need to exist.

I think that's a very bad pattern. Old binaries do need to at least be supported with security upgrades and to ensure they remain compatible with the p2p network otherwise we'd need to maintain 13 different p2p networks.

**Comment by MicahZoltu** [comment]
> How else do you fork with only an honest minority and a dishonest majority without changing the validator set in some way.

People run clients with a new ruleset that is incompatible with the old ruleset and the system forks.  Validators that run the old ruleset will leak out of the new ruleset chain and validators that run the new ruleset will leak out of the old ruleset chain.

> Anyway, I think I may have confused you here. I wasn't really talking about forks, I just brought it up to say that this is an orthogonal process. It's purely to automate coordination. Instead of saying everyone needs to update at height 100. Everyone updates in their own time and then communicates to other nodes that they're ready to upgrade. When 2/3+ of the validator set have communicated their intention to upgrade, the next block proposer proposes a block with the new app version. If it gets accepted everyone then switches to the new version (this means of course that a binary will include two state machines: the old and the new).

The problem I see is that 2/3 may never come, in which case the group who wants to run the new ruleset is "blocked" from doing so by the 1/3+ group that doesn't want the new rules.  I think this could be resolved with a deadline where the fork happens at `min(2/3 validators signal,  deadline block height)`.  This way you can fork earlier than the target block if there is sufficient buy-in from validators, but the fork cannot be prevented by 1/3 of validators.

**Comment by cmwaters** [comment]
> I think that's a very bad pattern. Old binaries do need to at least be supported with security upgrades and to ensure they remain compatible with the p2p network otherwise we'd need to maintain 13 different p2p networks. It sounds like a long-term nightmare.

Yeah ideally you could use the latest version to process all txs since genesis. This might not be too difficult for Celestia if we think it will ossify rather quickly. But if the SDK supports one form of upgrading strategy it may be difficult to do another as we essentially need all txs to be versioned and a state machine capable of processing each version. 

> Old binaries do need to at least be supported with security upgrades

Hmm somewhat. If the network has moved on to a new version, say v2, then the only nodes running v1 are catching up. There is a far less threat surface to nodes catching up because they simply don't have the latest state so no-one is interested in them. Far more critical is the latest version which may have vulnerabilities that could take users funds for example.

**Comment by musalbas** [comment]
>Yeah ideally you could use the latest version to process all txs since genesis. This might not be too difficult for Celestia if we think it will ossify rather quickly. But if the SDK supports one form of upgrading strategy it may be difficult to do another as we essentially need all txs to be versioned and a state machine capable of processing each version.

I think that's how Bitcoin and Ethereum work, afaik.

**Comment by evan-forbes** [comment]
closing as celestia-app is currently reliant upon a socially coordinated upgrade. Note that this is different from any flavor of signalling

**Comment by MicahZoltu** [comment]
Where can one read more about this "socially coordinated upgrade" process?
