### ISSUE TITLE
Pre-Incentivized testnet IBC things

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1125]
We still have some IBC related things that we would like to complete by the incentivized testnet feature freeze. The main three are already in progress and should be fairly straight forward, which involve enabling IBC in the first place

- [x] https://github.com/celestiaorg/celestia-core/pull/906
- [x] https://github.com/celestiaorg/cosmos-sdk/pull/288
- [x] https://github.com/celestiaorg/celestia-app/issues/412
- [x] https://github.com/celestiaorg/celestia-app/issues/235
- [x] The IBC portion of https://github.com/celestiaorg/celestia-app/issues/658 [comment](https://github.com/celestiaorg/celestia-app/pull/696#discussion_r1004252699)

I don't think we have social consensus yet on anything, but one simple idea that could be a good starting point would also be looking into only allowing transfers of Celestia tokens https://github.com/celestiaorg/celestia-app/pull/696#discussion_r1004251957 .

**Comment by cmwaters** [comment]
I've been following the various conversations happening around here just to gather as much context as possible and wanted to provide my view on a couple of these decisions:

**1. Shall Celestia be deployed with IBC?**
For me this is a resounding yes. Celestia depends on a marketplace whereby rollups can buy celestia tokens and validators and delegators can sell those tokens. This doesn't necessarily have to be through IBC (It most likely will be supported via centralized exchanges), but it's important to have that option there for users who prefer decentralised exchanges. 

**2. Should the Celestia network support anything else than the transferring of Celestia tokens?**
I'm in agreement with what Ismail said about being as minimal as possible and like Zaki's suggestion. I think only the `transfer` module should be supported and only channels with the Celestia denomination should be allowed. There is no supported use case for any other denomination than the Celestia native token on Celestia. With that in mind, it shouldn't allow anything else by design. 

**3. Should we limit which chains connect with Celestia?** 
In alignment with the "permissionless" ethos, I think we should allow users to send Celestia tokens to and from whatever chain they want so long as it's sufficiently compensated. If we feel the resources for supporting IBC is incorrectly calculated we can modify this. We may want to put more emphasis on high throughput chains over lower throughput chains by increasing the gas to open connections and lowering the gas per transfer across the channel. 

Are there any other questions on this topic we feel need to be resolved before mainnet launch? Does anyone have stronger opinions against the stances I've put forward i.e. should we set up a meeting in the near future to discuss these points? @evan-forbes @adlerjohn @liamsi @musalbas

**Comment by musalbas** [comment]
In general I am in favor of enabling IBC for Celestia's native token, but I'd quite like to know the resource pricing for IBC for sanity checking

**Comment by cmwaters** [comment]
> but I'd quite like to know the resource pricing for IBC for sanity checking

Okay I'll start to do some research on that

**Comment by cmwaters** [comment]
So looking into the IBC repository, it seems that there are no adjustments to gas consumption outside of how the SDK normally calculates it i.e. writes and reads to the kvstore (and signature verification) as follows: 

```go
// KVGasConfig returns a default gas config for KVStores.
func KVGasConfig() GasConfig {
	return GasConfig{
		HasCost:          1000,
		DeleteCost:       1000,
		ReadCostFlat:     1000,
		ReadCostPerByte:  3,
		WriteCostFlat:    2000,
		WriteCostPerByte: 30,
		IterNextCostFlat: 30,
	}
}
```


The main messages we'd expect and the average gas consumed (on Cosmos Hub) are:

|  Msg | Gas | 
|------|------|
| [`MsgUpdateClient`](https://github.com/cosmos/ibc-go/blob/ca35138d8c3a204c05744b7e13a7953b6f392a61/proto/ibc/core/client/v1/tx.proto#L44)| ~350,000 |
| [`MsgTransfer`](https://github.com/cosmos/ibc-go/blob/ca35138d8c3a204c05744b7e13a7953b6f392a61/proto/ibc/applications/transfer/v1/tx.proto#L20) |  ~90,000 | 200,000 |
|[`MsgRecvPacket`](https://github.com/cosmos/ibc-go/blob/866bb9afddb77d6461f52af62e566a95cab804ff/proto/ibc/core/channel/v1/tx.proto#L168)| ~80,000 |
| [`MsgAcknowledgement`](https://github.com/cosmos/ibc-go/blob/866bb9afddb77d6461f52af62e566a95cab804ff/proto/ibc/core/channel/v1/tx.proto#L228) | ~30,000 | 

From looking into the code, IBC keeps as minimal amount of state as possible so the overhead per connection with a chain is actually quite low.

**Comment by musalbas** [comment]
Is it the case that for example, IBC packets that contain more signatures (because the chain's validator set is bigger) or have higher proof size, would have higher gas?

**Comment by musalbas** [comment]
>In the SDK, all signatures have an additional "computational" cost (i.e. 590 gas for each ed25519 signature) but although IBC also verifies signatures, I don't believe it consumes gas. I have created an issue in their repo about it: https://github.com/cosmos/ibc-go/issues/2951

Why is it the case that normal signatures cost gas, but IBC ones don't?

**Comment by cmwaters** [comment]
I'm not sure if there was any intention behind it. From what I gather, the SDK decided that signature verification is costly enough to consider charging gas for verifying the signer of each `sdk.Tx`. The validator signatures in IBC are inside the messages of the Tx itself (specifically `MsgUpdateClient`), so the SDK is unaware of it and either IBC decided it didn't make sense, it was too difficult to implement (it's hard to know how many signatures needed to be verified), or that they simply missed it.

**Comment by evan-forbes** [comment]
> In general I am in favor of enabling IBC for Celestia's native token

To move forward with this, I think we can progress to #235, where we aim to find out what is needed to limit IBC to only Celestia's native token.

I, or @cmwaters, can talk with the IBC to see what the particular reason was for not charging gas, and then weight our options from there. In the future, I imagine that we should be able to add gas costs to those signatures if it becomes an issue.

**Comment by evan-forbes** [comment]
closing, as we've merged our initial restrictions on IBC and enabled it. We will still document the gas usage, specifically how we are not currently charging gas for signatures and the values above, in #658

**Comment by evan-forbes** [comment]
we also have a follow up for more thorough, yet slightly complex e2e tests for IBC connections to chains such as osmosis and cosmos hub in #1249, and then we will include the implemented token filter in specs in #734
