### ISSUE TITLE
EPIC: Usage Documentation

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1257]
We are already trying to have some form of accurate specs in celestiaorg/celestia-app#650, which will help a lot in terms of documentation, but we still need a lot of documentation relating to usage of code related to core/app.

- [ ] celestiaorg/celestia-app#397 (could also have a copy in the specs)
- [x] celestiaorg/celestia-app#870
- [x] https://github.com/celestiaorg/celestia-app/issues/1113
- [x] celestiaorg/celestia-app#1267
- [ ] https://github.com/celestiaorg/celestia-app/issues/1321

### QGB related
- [x] celestiaorg/celestia-app#1254 
- [x] celestiaorg/celestia-app#956 
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/2
- [x] https://github.com/celestiaorg/celestia-core/issues/925

**Comment by cmwaters** [comment]
I would also add here: documenting of IBC's token filter middleware

**Comment by evan-forbes** [comment]
we have yet to complete #1321, however the rest of the points have been addressed and this epic is a bit stale. 

If we want to prioritize other efforts for usage documentation we should create a new epic with updated issues
