### ISSUE TITLE
Consider increasing the namespace id size

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1308]
## Context

In Slack, we discussed that it would be difficult to change the namespace id size post mainnet launch because such a change has implications on the NMT, share encoding, etc.

## Proposal

Consider increasing the namespace id size from 8 bytes to something larger.

## Tasks
- [x] https://github.com/celestiaorg/celestia-app/pull/1405
- [x] https://github.com/celestiaorg/celestia-app/pull/1419
- [x] https://github.com/celestiaorg/celestia-app/issues/1453

cc: @musalbas

**Comment by rootulp** [comment]
Napkin math:

256 ^ 8 = 1.84467441e19
256 ^ 10 = 1.20892582e24
256 ^ 16 = 3.40282367e38

**Comment by rootulp** [comment]
When implementing this, inform @staheri14 that it will involve a change to NMT and the spec

**Comment by rootulp** [comment]
| Namespace ID size (in bytes) | % of 512 byte share |
|------------------------------|---------------------|
| 8                            | 1.5%                |
| 16                           | 3.1%                |
| 20                           | 3.9%                |
| 32                           | 6.2%                |

## Notes

- [SHA256](https://en.wikipedia.org/wiki/SHA-2) has a digest size of 32 bytes so using a namespace ID size of 32 bytes would enable users to generate stable namespace IDs (e.g. `sha256('sov-labs')`) or unique namespace IDs (e.g. `sha256(blob)`)
- [IPv6](https://en.wikipedia.org/wiki/IPv6) has an address space of 16 bytes [source](https://en.wikipedia.org/wiki/IPv6#Addressing)

    > the address space is deemed large enough for the foreseeable future

- The size of Ethereum's private key space is 2^256 (32 bytes) [source](https://github.com/ethereumbook/ethereumbook/blob/develop/04keys-addresses.asciidoc)
- The size of Ethereum's address space is 2^160 (20 bytes) [source](https://github.com/ethereumbook/ethereumbook/blob/05f0dfe6c41635ac85527a60c06ac5389d8006e7/04keys-addresses.asciidoc)
- The size of Bitcoin's address space is 2^160 (20 bytes) [source](https://www.coinhouse.com/insights/news/what-if-my-wallet-generated-an-existing-bitcoin-address/)
- The size of Fuel's contract ID is 32 bytes [source](https://fuellabs.github.io/fuel-specs/master/protocol/id/contract.html)
- The size of Fuel's address space is either 20 bytes [source](https://docs.fuel.sh/v1.1.0/Concepts/Data%20Structures/Addresses.html#addresses) or 32 bytes [question](https://github.com/FuelLabs/fuel-docs/issues/75)
