### ISSUE TITLE
Testnet Tracking Issue

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#152]
### Summary

Here are the issues we are aiming to address before testnet. Essentially, we will attempt re-write most of the existing logic in celestia-core in the app. We might not be able to use stock tendermint at first, but that is the goal for mainnet. This will be done by using the `PrepareProposal` and [`ProcessProposal`](https://github.com/tendermint/tendermint/pull/7091) portions in the [abci++](https://github.com/tendermint/tendermint/tree/abci%2B%2B)  branch. This list is not yet complete, and some features might not be possible without ABCI++.

### ABCI++
- [x] Adopt simplified version of ABCI++ celestiaorg/celestia-core#231 

### Filling the data square
- [ ] Implement non-interactive defaults [#455](https://github.com/celestiaorg/celestia-core/issues/455)
- [x] Mechanism to efficiently and safely fill the square [#454](https://github.com/celestiaorg/celestia-core/issues/454) 
- [x] Adopt Reaping from the mempool to max square size [#77](https://github.com/celestiaorg/celestia-core/issues/77)

### Bad Encoding Fraud Proof
- [ ] Implement BadEncodingFraudProof [#461](https://github.com/celestiaorg/celestia-core/issues/461)

### Check for message inclusion
- [x] ADR for message inclusion check [#520](https://github.com/celestiaorg/celestia-core/issues/520)
- [ ] Create API to check for message inclusion [#565](celestiaorg/celestia-app#381)

### Maintenance/Bug fixes/Misc
- [x] celestiaorg/celestia-core#144  
- [ ] Debug why WirePayForMessages are not removed from the mempool when rechecking transactions [#584](https://github.com/celestiaorg/celestia-core/issues/584)
- [ ] Decide on signing over the PartSetHeader [#511](https://github.com/celestiaorg/celestia-core/issues/511)
- [x] celestiaorg/celestia-core#39
- [x] celestiaorg/celestia-node#3
- [ ] Quick and dirty fee burning
- [ ] Changing the default consensus timeouts [#585](https://github.com/celestiaorg/celestia-core/issues/585)
- [x] Support malleated transactions in the event system [#590](https://github.com/celestiaorg/celestia-core/issues/590)

### Stretch Goals
- [ ] Check that only paid for messages are included in the block
- [ ] Proper fee burning celestiaorg/celestia-core#49 
- [ ] Message inclusion fraud proofs [#519](https://github.com/celestiaorg/celestia-core/issues/519)
- [ ] gas optimize the quantum gravity bridge (e.g. BLS sigs)

## Quantum Gravity Bridge

- [x] contracts: nmt verification https://github.com/celestiaorg/quantum-gravity-bridge/issues/6
- [ ] contracts: parsing out shares https://github.com/celestiaorg/quantum-gravity-bridge/issues/18
- [ ] orchestrator: change to send data to contract only https://github.com/celestiaorg/quantum-gravity-bridge/issues/9
- [x] orchestrator: decide on either merkelize and send tuples to contract, or, use existing data root and implement accordingly https://github.com/celestiaorg/quantum-gravity-bridge/issues/20
- [ ] orchestrator: read tuples from app/node (depends on the above decision) https://github.com/celestiaorg/quantum-gravity-bridge/issues/19
- [ ] deploy on ETH test-net 🎉 🚀 

## EVMOS settlement rollup hub

- [ ] complete and stabilize EVMOS ontop of optimint integration (https://github.com/celestiaorg/optimint/issues/189, https://github.com/celestiaorg/optimint/issues/49)
- [ ] run it as part of CI/CD pipeline (@jbowen93, @Bidon15) 
- [ ] customize and deploy Arbitrum on top of EVMOS rollup
- [ ] planning goal: spec out and implement state fraud proofs for the EVMOS settlement rollup
- [ ] stretch/planning goal: decide and spec out _leader selection_ for Evmos rollup (could be in solidity or a modified version of the staking module)

## Celestia Node
See [ADR](https://github.com/celestiaorg/celestia-node/blob/8e42e6a41e237d4f109680afb4545cff47a55013/docs/adr/adr-003-march2022-testnet.md) for details.
- [ ] State Machine Integration (ability for node to recompute state independent tendermint+app)
- [ ] Bad Encoding Fraud Proofs
- [ ] RPC framework + APIs

## Optimint

- [ ] integrate Optimint with Celestia DA layer (https://github.com/celestiaorg/optimint/issues/64)

**Comment by evan-forbes** [comment]
closing as this tracking issue is outdated
