### ISSUE TITLE
EPIC: Implement ADR 13

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1538]
## Context

Per an onsite meeting, we decided to move forward with [ADR 13](https://github.com/celestiaorg/celestia-app/blob/main/docs/architecture/adr-013-non-interactive-default-rules-for-zero-padding.md).

## Next steps

- [ ] Determine a threshold for the size of a blob inclusion proof. This likely requires discussion with @celestiaorg/celestia-node 
- [ ] Assuming a threshold where the # of subtree roots in a blob inclusion proof is bounded by the max square size, does padding change if the max square size increases in a subsequent hard-fork but the threshold remains the same?
- [x] https://github.com/celestiaorg/celestia-app/issues/1572
- [x] #1606
- [x] #1607

Any other follow-ups @nashqueue?

**Comment by nashqueue** [comment]
- [ ] How does it affect zk-rollups? In general, what are the options for zk-rollups to verify blob inclusion?

**Comment by evan-forbes** [comment]
can close since the implementation has been merged and documented
