### ISSUE TITLE
system/load/testing: load a full validator set with max block sizes for a day

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#1643]
This is a kick-start of load testing on system level. This part involves developing a test-suite that is executed every new release: 

```[tasklist]
### Tasks
- [ ] Prepare robusta k8s to deploy a 100 validator set
- [ ] It should contain metrics/traces/logging possibilities for the team to have observability
- [ ] Develop a test-client that will constantly flow with TXs making every block full
- [ ] The scenario is active for 24hr 
- [ ] A GH action that notifies on test execution status 
```

**Comment by evan-forbes** [comment]
this was done on mocha when it was spammed with large IBC txs. we should probably repeat similar tests after mocha increases block size.
