### ISSUE TITLE
EPIC: Manual testing checklist for acceptance level

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#1696]
Introduction 🧐 
---

As mocha testnet is the closest environment we have to upcoming mainnet, we need to make sure that users can actually experience all features we are shipping. Hence why we need to clarify features we want to test as users ourselves. 

List of features 📝 
---
we need to go through with every new release on mocha: 

```[tasklist]
### Tasks
- [ ] Ledger Nano S/X
- [ ] Keplr Wallet
- [ ] Any other wallets
- [ ] Multi-sigs
- [ ] IBC Filtering
- [ ] Authz
- [ ] Staking
- [ ] Vesting
- [ ] Block explorer data
- [ ] TX send / multi-send
```

2c on long-term strategy: we can either do it alone, or ask for community help here

User Bugs 🐞  
---

- [x] https://github.com/celestiaorg/celestia-app/issues/1658

**Comment by evan-forbes** [comment]
can we rename this to "Manually test application" or something that indicates that this epic is explicitly for that?

**Comment by evan-forbes** [comment]
closing as completed
