### ISSUE TITLE
Epic: Rollup UX

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#1939]
### Summary

One of the main pillars to focus on following mainnet release is how we can improve the UX specifically for rollups building on top of Celestia. For the consensus layer this predominantly resides around the "transaction" itself - how can we provide a simple and robust system for users to submit their PFBs, how can we improve the guarantees around submission, how do we provide introspection across the lifecycle of a transaction, how do we prevent spam. This is a tracking issue for Rollup UX. Obviously, it would be super helpful to get continual feedback from some of our rollup developers.

**Short term targets**

- [ ] #1910 - Rearrange multiple txs by the same sender according to nonce to decrease the likelihood that they're invalid
- [ ] #1937
- [ ] #1916 - Introduce a MinGasPFBDecorator to ensure that PFBs have sufficient gas (this helps to avoid txs from running out of gas and users getting DA for free)
- [ ] Nonce lanes to allow for replay protection without strict serialization. Users can submit multiple txs without having to worry about how Celestia orders transactions.
- [ ] Gas refunds that mean users can safely overestimate gas without having to worry about paying too much for their PFBs
- [ ] #1773 and #1546
- [ ] PFB specific feegrants to support distributed rollup systems and/or better key management.

**Mid term but needs further discussion / product exploration**

- [ ] #1621 - or more generally work towards a cohesive fee market that provides predictable, competitive and fair pricing for data availability
- [ ] Publish continual data around the current minimum gas price for a transaction to get in a block. This can inform rollups if they need to increase spending.
- [ ] Atomic PFBs (can submit multiple messages in a single BlobTx)
- [ ] Use a simple secondary index instead of the kv indexer for tracking the status of transactions: In the mempool, rejected, committed etc.. 
- [ ] Explore using gas price ranges (Users attaches the maximum price they are willing to pay for the tx to make it into the next block)
- [ ] Research more thoroughly into the tradeoff between block times and block efficiency. 

**Long term targets**

- [ ] Improve single block censorship resistance through a multi-proposer protocol (potentially a DAG based consensus or usage of VoteExtensions)
- [ ] Have a uniform API across all nodes (both DA and consensus) that rollups can communicate with.
- [ ] Feature namespaces: subset of namespaces that have certain features that are desirable for some rollup users. This could be having a namespace nonce to avoid duplicate submission; having permissioned namespaces; some namespaces could use threshold decryption for censorship resistance
- [ ] Support multiple fee tokens

This focuses just on rollup SDKs and developers. There are other classes of users: validators, infrastructure etc. whose experience using Celestia we should also look to improve.

### Problem Definition

f

### Proposal

f

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
could we ever get
> Support multiple fee tokens

and 

> EIP1559 style min fee #1621

since the min fee for two different tokens would require pricing information?
