### ISSUE TITLE
EPIC: Knuu e2e tests

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2061]
As the we are all preparing to switch to a common e2e test framework, we will need to flesh out the core/app portion. This portion needs to be able to act not only as an e2e test for core/app, but also as a foundation for repos built ontop of the celestia blockchain such as light clients and rollups.

This core/app portion of the framework will mainly be focused on regression testing and not correctness. For example, we will eventually want to test all things relating to single binary syncs/upgrades https://github.com/celestiaorg/celestia-app/issues/2033, malicious block production, and fuzzing for non-determinism. 

- [x] https://github.com/celestiaorg/celestia-app/pull/2370 
- [x] https://github.com/celestiaorg/celestia-app/pull/1914
- [x] https://github.com/celestiaorg/celestia-app/issues/313
- [ ] https://github.com/celestiaorg/celestia-app/issues/2414
