### ISSUE TITLE
EPIC: Release Candidate 12

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2256]
We have decided to include a few breaking changes in release candidate twelve. 

- [x] #2253
- [x] #2255 (also see #2169)
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/338

bonus:
- [x] https://github.com/celestiaorg/celestia-app/pull/2202
- [x] https://github.com/celestiaorg/celestia-app/pull/2217
- [x] https://github.com/celestiaorg/celestia-app/issues/2221
- [x] https://github.com/celestiaorg/celestia-app/issues/2195

**Comment by evan-forbes** [comment]
can close with #2300
