### ISSUE TITLE
EPIC: Short term block propagation improvements

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2811]
There are currently a few changes that should be easy to incorporate while potentially have a large impact on the efficiency and effectiveness of block propagation. We should investigate these individually by running experiments against a control network. For each of the listed experiments, we need **a report** that measures the difference in:

- Time required to gossip the proposal block
- Total bandwidth used per MB of block data per peer per channel
- Percentage of block parts received more than once
- Percentage of bandwidth used by each reactor over time
- Percentage of blocks

#### Experiments

- [ ] Further prioritize block part gossiping
- [ ] Use CAT
- [ ] Backport [#904](https://github.com/cometbft/cometbft/pull/904) and/or some equivalent
- [ ] reduced number of peers but increased bandwidth rate limits

--------------- (bonus)
- [ ] erasure encode the proposal block

**Comment by staheri14** [comment]
Since reactors may be responsible for different channel IDs, it would be more insightful to get "percentage of bandwidth used by each _channel_ over time" (in replace of Percentage of bandwidth used by each _reactor_ over time).
