### ISSUE TITLE
WIP EPIC: V1 SNARK Accounts

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2895]
**WIP the contents of this EPIC are subject to change. Please see discussions below.**

## Intro

As initially described in [this forum post](https://forum.celestia.org/t/achieving-base-layer-functionality-escape-velocity-without-on-chain-smart-contracts-using-sovereign-zk-rollups/958/1), it is possible for the state machine to maintain a trust minimized and state minimized two way bridge to a rollup. This can be done by controlling an account with a SNARK instead of the normal signature.

Similar to a standard zk-rollup, the SNARK would prove that the state transitions for a given set of transactions or state diffs was computed correctly. However, to further minimize the state burden while maintaining the same trust minimized bridging, other things are proved as well. Specifically the inclusion of any txs or state diff, the fork choice rule, and the construction of the tx that is performing some action for the account.

### Trust Minimization

It should be impossible for any unauthorized party to perform an action for the SNARK Account. It should also not inherently require a third party to create and submit an authorized action for the SNARK account.

### State Minimization

Each SNARK Account should utilize the same or very similar amount of state to that of a normal account.

## Discussions

- https://github.com/celestiaorg/celestia-app/discussions/2902
- https://github.com/celestiaorg/celestia-app/discussions/2903
- https://github.com/celestiaorg/celestia-app/discussions/2904

## Issues

- [ ] Investigate and decide on an initial set of Required Public Inputs
- [x] #2905
- [x] #2906
- [ ] Write the CIP / spec
- [ ] Write the ADR

### Bonus

- [x] #2907
