### ISSUE TITLE
Tracker: Remaining tasks for QGB 1.0

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#301]
This issue will be a tracker for the remaining work for the QGB 1.0 to be finalized. New tasks will be added as they pop up.
For now, the QGB work is under the following branch: https://github.com/celestiaorg/celestia-app/tree/qgb-integration, and will be merged to master once we have a stable version.

#### Orchestrator and Relayer
- [x] https://github.com/celestiaorg/celestia-app/issues/320
- [x] https://github.com/celestiaorg/celestia-app/issues/270
- [ ] https://github.com/celestiaorg/celestia-app/issues/217
- [x] https://github.com/celestiaorg/celestia-app/issues/307
- [x] https://github.com/celestiaorg/celestia-app/issues/406
- [x] https://github.com/celestiaorg/celestia-app/issues/628

#### State machine
- [x] https://github.com/celestiaorg/celestia-app/issues/339
- [x] https://github.com/celestiaorg/celestia-app/issues/373
- [x] https://github.com/celestiaorg/celestia-app/issues/437
- [x] https://github.com/celestiaorg/celestia-app/issues/480
- [x] https://github.com/celestiaorg/celestia-app/issues/498
- [x] https://github.com/celestiaorg/celestia-app/issues/499
- [ ] https://github.com/celestiaorg/celestia-app/issues/501
- [x] https://github.com/celestiaorg/celestia-app/issues/502
- [x] https://github.com/celestiaorg/celestia-app/issues/507
- [x] https://github.com/celestiaorg/celestia-app/issues/518
- [x] https://github.com/celestiaorg/celestia-app/issues/520
- [x] https://github.com/celestiaorg/celestia-app/issues/521
- [x] https://github.com/celestiaorg/celestia-app/issues/631
- [x] https://github.com/celestiaorg/celestia-app/issues/638

#### Cosmos-sdk
- [ ] https://github.com/celestiaorg/cosmos-sdk/issues/129
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/143
- [ ] https://github.com/celestiaorg/cosmos-sdk/issues/144
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/220

#### CLI
- [x] https://github.com/celestiaorg/celestia-app/issues/451

#### Misc
- [x] https://github.com/celestiaorg/celestia-app/issues/326
- [x] https://github.com/celestiaorg/celestia-app/issues/506
- [x] https://github.com/celestiaorg/celestia-app/issues/517

#### Investigations

- [x] https://github.com/celestiaorg/celestia-app/issues/603
- [x] https://github.com/celestiaorg/celestia-app/issues/604

### High priority
- [x] https://github.com/celestiaorg/celestia-app/issues/482
- [ ] https://github.com/celestiaorg/celestia-app/issues/243
- [x] https://github.com/celestiaorg/celestia-app/issues/303
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/136
- [x] https://github.com/celestiaorg/celestia-app/issues/479
- [x] https://github.com/celestiaorg/celestia-app/issues/522
- [x] https://github.com/celestiaorg/celestia-app/issues/532
- [ ] https://github.com/celestiaorg/celestia-app/issues/533
- [x] https://github.com/celestiaorg/celestia-app/issues/546
- [x] https://github.com/celestiaorg/celestia-app/issues/552
- [x] https://github.com/celestiaorg/celestia-core/issues/837
- [ ] https://github.com/celestiaorg/celestia-app/issues/744
- [ ] https://github.com/celestiaorg/celestia-app/issues/745
- [ ] https://github.com/celestiaorg/celestia-app/issues/768

### Low priority
- [x] https://github.com/celestiaorg/celestia-app/issues/259
- [x] https://github.com/celestiaorg/celestia-app/issues/262
- [x] https://github.com/celestiaorg/celestia-app/issues/305
- [x] https://github.com/celestiaorg/celestia-app/issues/306
- [ ] https://github.com/celestiaorg/quantum-gravity-bridge/issues/71
- [x] https://github.com/celestiaorg/celestia-app/issues/503
- [x] https://github.com/celestiaorg/celestia-app/issues/504
- [x] https://github.com/celestiaorg/celestia-app/issues/505
- [x] https://github.com/celestiaorg/celestia-app/issues/752

## Already done
- [x] https://github.com/celestiaorg/celestia-app/issues/278
- [x] https://github.com/celestiaorg/celestia-app/issues/268
- [x] https://github.com/celestiaorg/celestia-app/issues/264
- [x] https://github.com/celestiaorg/celestia-app/issues/248
- [x] https://github.com/celestiaorg/celestia-app/issues/258
- [x] https://github.com/celestiaorg/celestia-app/issues/223
- [x] https://github.com/celestiaorg/celestia-app/issues/220
- [x] https://github.com/celestiaorg/celestia-app/issues/198
- [x] https://github.com/celestiaorg/celestia-app/issues/283
- [x] https://github.com/celestiaorg/celestia-app/issues/298
- [x] https://github.com/celestiaorg/celestia-app/issues/302
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/114
- [x] https://github.com/celestiaorg/celestia-app/issues/304
- [x] https://github.com/celestiaorg/celestia-app/issues/308
- [x] https://github.com/celestiaorg/celestia-app/issues/324
- [x] https://github.com/celestiaorg/celestia-app/issues/325
- [x] https://github.com/celestiaorg/celestia-app/issues/327
- [x] https://github.com/celestiaorg/celestia-app/issues/328
- [x] https://github.com/celestiaorg/celestia-app/issues/329
- [x] https://github.com/celestiaorg/celestia-app/issues/334
- [x] https://github.com/celestiaorg/celestia-app/issues/335
- [x] https://github.com/celestiaorg/celestia-app/issues/343
- [x] https://github.com/celestiaorg/celestia-app/issues/349
- [x] https://github.com/celestiaorg/celestia-app/issues/353
- [x] https://github.com/celestiaorg/celestia-app/issues/356
- [x] https://github.com/celestiaorg/celestia-app/issues/362
- [x] https://github.com/celestiaorg/celestia-app/issues/370
- [x] https://github.com/celestiaorg/celestia-app/issues/374
- [x] https://github.com/celestiaorg/celestia-app/issues/398
- [x] https://github.com/celestiaorg/celestia-app/issues/403
- [x] https://github.com/celestiaorg/celestia-app/issues/407
- [x] https://github.com/celestiaorg/celestia-app/issues/409
- [x] https://github.com/celestiaorg/celestia-app/issues/428
- [x] https://github.com/celestiaorg/celestia-app/issues/438
- [x] https://github.com/celestiaorg/celestia-app/issues/463
- [x] https://github.com/celestiaorg/celestia-app/issues/467
- [x] https://github.com/celestiaorg/quantum-gravity-bridge/issues/120

**Comment by evan-forbes** [comment]
### Context

We've been iterating on the design the orchestrator and relayer over the past few weeks in the `qgb-integration` branch. This has been incredibly helpful in figuring out exactly what needs to be done, how it should be done, along with continually refactoring how the team works best together. While reviewing this features branch will take time, and be done in chunks, I do believe that it will save reviewers time, and allow for a proper final review, instead of having to review each refactor. 

### Merging the feature branch

The plan to merge the `qgb-integration` branch into master is to first finish the above tasks and merge them into the `qgb-integration` branch. At this point, a fully functional QGB 1.0 (not MVP!) will be completed.

The final review process will begin with the review of the QGB 1.0 ADR #270. After that, we will cherry-pick chunks of the final iteration of the qgb into master. After this process is complete, we will cut a new breaking release of the app.

**Comment by evan-forbes** [comment]
todo: move remaining issues to other epics, tracking issues, and/or repos

closing because we are no longer tracking v1
