### ISSUE TITLE
QGB MVP tracker

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#320]
This issue will track the remaining tasks required to finish the QGB MVP, ie a simple minimal version that only does the following:
- Deploy the bridge smart contract
- Sign Valsets
- Sign data commitments
- Relay the signed confirms to Ethereum

- [x] https://github.com/celestiaorg/celestia-app/issues/315
- [x] https://github.com/celestiaorg/celestia-app/issues/316
- [x] https://github.com/celestiaorg/celestia-app/issues/317
- [ ] https://github.com/celestiaorg/celestia-app/issues/318
- [x] https://github.com/celestiaorg/celestia-app/issues/319
- [x] https://github.com/celestiaorg/celestia-app/issues/321
- [x] https://github.com/celestiaorg/celestia-app/issues/329
- [x] https://github.com/celestiaorg/celestia-app/issues/353
- [x] https://github.com/celestiaorg/celestia-app/issues/363
- [x] https://github.com/celestiaorg/celestia-app/issues/364
- [x] https://github.com/celestiaorg/celestia-app/issues/366

**Comment by liamsi** [comment]
My suggestion is to deploy this on testnet already. Even after we launched it: someone (@SweeXordious, @evan-forbes or @adlerjohn) should submit a gov proposal and we should upgrade whenever we are ready.

**Comment by evan-forbes** [comment]
per sync discussion, this issue can be closed due to moving to v2
