### ISSUE TITLE
EPIC: Preventing and preparing for non-determinism between app versions

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3475]
Currently, we have [minor version bump tests in knuu](https://github.com/celestiaorg/celestia-app/blob/39301655ba51010296e4e79963700cc1ae80008b/test/e2e/check_upgrades.go#L24). This test is great because it performs a simple test for non-determinism between minor versions. However, we likely need to either expand on this test or create new tests that expand on what portions of the state-machine and block validity rules are covered. While not required, ideally we would be able to run some tests upon each push, or at least after being merged to main.

- [x] https://github.com/celestiaorg/celestia-app/issues/2414
- [x] https://github.com/celestiaorg/celestia-app/issues/3540

Unless we are 100% confident that the tests cover every case, then we also need to be prepared to debug non-determinism issues. 
- [ ] https://github.com/celestiaorg/cosmos-sdk/issues/397
- [ ] https://github.com/celestiaorg/cosmos-sdk/issues/398

**Comment by evan-forbes** [comment]
closing as completed
