### ISSUE TITLE
Tracking: Non-interactive defaults

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#382]
With our current message inclusion check, we are not checking the location of the messages, only that each message has a corresponding commitment in a `MsgPayForData`. This works for ensuring that each message was included, but this doesn't actually check that the commitment is actually a subtree root to one of the data availability header row or column roots.

In order to do this, we have to have block producers organize the message layout to follow the [non-interactive defaults](https://github.com/celestiaorg/celestia-specs/blob/master/src/rationale/message_block_layout.md). This will involve a refactor during the app's `PrepareProposal` call, along with adding the message [starting location to wrapped txs](https://github.com/celestiaorg/celestia-core/issues/462#issuecomment-1118738645).

Additionally, we need validators and full nodes to check that each share commitment is actually a subtree root to one of the data availability headers. This will require a refactor to the app's `ProcessProposal` call, and is blocked by the functionality described in the above paragraph.

- [x] Add `MessageStartIndex` field to the [malleated transactions](https://github.com/celestiaorg/celestia-core/blob/7e29d6560b7e2c96c60c2c5b2ae5d9e371e382d8/proto/tendermint/types/types.proto#L221-L227) struct https://github.com/celestiaorg/celestia-core/issues/462
- [x] Create a good API for checking for subtree root inclusion #381
- [x] Refactor `PrepareProposal` to organize the message layout according to the non-interactive defaults
- [x] #383

A **huge bonus** would be if we would also implement message inclusion fraud proofs, but this does not have to be completed to close this issue

**Comment by evan-forbes** [comment]
I have this listed as an incentivized testnet feature for now, as I don't think we will have it ready in time for testnet considering our other priorities, BUT we can (and should imho) obviously include this in an upgrade to testnet after we finish.

**Comment by evan-forbes** [comment]
The current plan for introducing features from the non-interactive defaults branch is to first review the library code:

#### Message inclusion
- [ ] https://github.com/celestiaorg/celestia-app/pull/549
- [ ] https://github.com/celestiaorg/celestia-app/pull/621
- [ ] General purpose API for ProcessProposal and celestia-node

#### Encoding
- [ ] #623 
- [ ] General refactor
- [ ] Add non-interactive defaults logic

#### Modify ABCI++ methods
- [ ] PrepareProposal Refactor to fill the square using non-interactive defaults
- [ ] ProcessProposal Refactor to check for message inclusion using sub tree roots

#### Documentation
- [ ] #598

notes: feature [branch](https://github.com/celestiaorg/celestia-app/tree/evan/non-interactive-defaults-feature)

**Comment by rootulp** [comment]
[Question] I discovered https://github.com/celestiaorg/celestia-core/blob/v0.34.x-celestia/pkg/prove/proof.go#L101-L109 which assumes that there is no padding between compact shares. Does `TxInclusion` in celestia-core also need to be updated to adhere to non-interactive-defaults behavior?

**Comment by evan-forbes** [comment]
> I discovered https://github.com/celestiaorg/celestia-core/blob/v0.34.x-celestia/pkg/prove/proof.go#L101-L109 which assumes that there is no padding between compact shares. Does TxInclusion in celestia-core also need to be updated to adhere to non-interactive-defaults behavior?

whoops yeah great point, forgot to write this down. it definitely will, as creating proofs requires the entire row, which will likely include message shares. 

as mentioned in the audit this morning by Sergio, we should look into how to use the blockstore in the app, we might just be able to move that endpoint there. It might slightly annoying to change in the sdk, but totally doable assuming that we can pass access to the block store in the app. iirc, the sdk often assumes that the endpoint is just running locally, so there might not even be a needed change in the sdk. 

we could also move over the data commitment rpc endpoint if that's the case
