### ISSUE TITLE
Tracking: testing, stability, and documentation

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#411]
In order to set our testnet up for success, we want to expand our existing unit tests, create new integration tests, and better document our code. This issue's purpose is to track all the current tasks related to those goals. We might not be able close all of these by testnet launch, but at least by testnet upgrade. 

### Expanding Current Testing
- [x] https://github.com/celestiaorg/celestia-app/issues/400
- [x] https://github.com/celestiaorg/celestia-app/issues/389
- [x] https://github.com/celestiaorg/celestia-app/issues/312
- [x] https://github.com/celestiaorg/celestia-app/issues/333

### New Integration tests
- [x] https://github.com/celestiaorg/celestia-app/issues/410

### Bugs
- [x] https://github.com/celestiaorg/celestia-app/issues/379
- [x] https://github.com/celestiaorg/celestia-app/issues/530

### Misc
- [X] https://github.com/celestiaorg/celestia-app/issues/323
- [x] https://github.com/celestiaorg/celestia-app/issues/279
- [x] #440 
- [x] https://github.com/celestiaorg/celestia-app/issues/244
- [x] https://github.com/celestiaorg/celestia-app/issues/755

it should be noted that while we could focus on tests like those described in #233, I think we can postpone these until after testnet, as those tests ensure that a malicious validator cannot propose improper blocks, as opposed to simply testing for proper honest functionality first.

**Comment by evan-forbes** [comment]
moved remaining issue directly to #514 so we can close this
