### ISSUE TITLE
Update the QGB implementation to support Universal nonce

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#467]
As per the [relayer security ADR](https://github.com/celestiaorg/celestia-app/pull/464),  we decided to move on with the universal nonce approach.
This issue will track the required changes needed to implement it:

- [x] https://github.com/celestiaorg/celestia-app/issues/268
- [ ] https://github.com/celestiaorg/celestia-app/issues/468
- [x] https://github.com/celestiaorg/quantum-gravity-bridge/issues/118
- [ ] https://github.com/celestiaorg/celestia-app/issues/469
- [ ] https://github.com/celestiaorg/celestia-app/issues/470
