### ISSUE TITLE
Incentivized Testnet Tracking Issue

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#514]
## Incentivized Testnet

This issue is meant to help track the remaining issues for incentivized testnet for both core/app. We will probably not be able to finish all of these things, but 

### Picking Parameters and Defaults
- [ ] https://github.com/celestiaorg/celestia-app/issues/413
- [ ] https://github.com/celestiaorg/celestia-app/issues/256
- [ ] https://github.com/celestiaorg/celestia-app/issues/169

### Non-interactive defaults 
- [ ] https://github.com/celestiaorg/celestia-app/issues/382

### Docs, Stability, and additional Testing
- [ ] https://github.com/celestiaorg/celestia-app/issues/411
- [ ] https://github.com/celestiaorg/celestia-app/issues/513

### State Machine
- [ ] https://github.com/celestiaorg/celestia-app/issues/412
- [ ] https://github.com/celestiaorg/celestia-app/issues/280
- [ ] https://github.com/celestiaorg/celestia-app/issues/235

### Misc
- [ ] https://github.com/celestiaorg/celestia-core/issues/673
- [ ] https://github.com/celestiaorg/celestia-core/issues/724

#### Will save us time in the future, as we could avoid a hard fork/migrations
- [ ] https://github.com/celestiaorg/celestia-app/issues/511
- [ ] https://github.com/celestiaorg/celestia-app/issues/431
- [ ] https://github.com/celestiaorg/celestia-app/issues/57
- [ ] https://github.com/celestiaorg/celestia-core/issues/722

#### Can be done whenever
- [ ] https://github.com/celestiaorg/celestia-app/issues/489
- [ ] https://github.com/celestiaorg/celestia-app/issues/485
- [ ] https://github.com/celestiaorg/celestia-app/issues/434
- [ ] https://github.com/celestiaorg/celestia-app/issues/405
- [ ] https://github.com/celestiaorg/celestia-app/issues/377
- [ ] https://github.com/celestiaorg/celestia-app/issues/284
- [ ] https://github.com/celestiaorg/celestia-app/issues/236
- [ ] https://github.com/celestiaorg/celestia-app/issues/233

#### Needs more investigation
- [ ] https://github.com/celestiaorg/celestia-core/issues/759
- [ ] https://github.com/celestiaorg/celestia-core/issues/757
- [ ] https://github.com/celestiaorg/celestia-core/issues/438

**Comment by evan-forbes** [comment]
we still have some parameters to pick, but this issue is mostly completed, and we aren't using it any longer, so I'm closing it for now
