### ISSUE TITLE
Tracker: tasks for the state machine portion QGB 2.0

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#516]
This issue will be a tracker for the work for the QGB 2.0. New tasks will be added as they pop up.

## Must have
- [x] https://github.com/celestiaorg/celestia-app/issues/309
- [x] https://github.com/celestiaorg/celestia-app/issues/332
- [x] https://github.com/celestiaorg/celestia-app/issues/683
- [x] https://github.com/celestiaorg/celestia-app/issues/684
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/3
- [x] https://github.com/celestiaorg/celestia-app/issues/843
- [x] https://github.com/celestiaorg/celestia-app/issues/879

**Comment by evan-forbes** [comment]
closing as outdated and it looks like we finished most things
