### ISSUE TITLE
EPIC: staking: update according to spec

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#56]
The specification makes some changes to the staking logic used internally in the cosmos-sdk: 
 - https://github.com/lazyledger/lazyledger-specs/blob/master/specs/consensus.md
 - https://github.com/cosmos/cosmos-sdk/tree/master/x/staking

Some of these changes are absolutely required for fraud proofs others are simplifications/optimizations.

Concrete action items for this issue (should be split into multiple issues/prs):
 - [ ] fully understand and document the diff between the spec and the cosmos-sdk
 - [ ] triage which parts of above diff are essential to launch LL and which are optimizations
 - [ ] create issues that describe the changes necessary (and where they have to be implemented: here (preferrably) or in the SDK if necessary)
 - [ ] implement above changes.

While the implementation can happen as late as the incentivized testnet, all other todos should be tackled earlier as they will determine how much work this actually is.

**Comment by liamsi** [comment]
Moved to incentivized testnet milestione for now.

**Comment by evan-forbes** [comment]
pushing this to after post mainnet, as that's when we're scheduled to do fraud proofs
