### ISSUE TITLE
EPIC: Universal share prefix

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#659]
We want to switch to more universal share encoding format, similar to what is discussed in  https://github.com/celestiaorg/celestia-core/issues/839. The main benefit of this approach being that parsing shares should be more similar in that we add a varint length delimiter to the total length of contiguous shares. 

> nid (8 bytes) | info byte | message length (varint) | share data for shares at the start of a message;
nid (8 bytes) | info byte | share data for other shares.

This means that the current format for contiguous shares (reserved namespace shares) will look like 

starting shares (last info bit == 1)
```nid (8 bytes) | info byte | message length (varint) | reserved byte | share data``` 
non starting shares (last info bit == 0)
```nid (8 bytes) | info byte | reserved byte | share data``` 

note that depending on what we decide for https://github.com/celestiaorg/celestia-core/issues/842, this issue might be moved to core.

**Comment by rootulp** [comment]
### Currently

#### Contiguous shares 

#### Non-contiguous shares (shares that don't use a reserved namespace. Ex. messages)

### Proposed

#### Contiguous shares (shares that use a reserved namespace. Ex. transactions, ISRs, evidence)

#### Non-contiguous shares (shares that don't use a reserved namespace. Ex. messages)

**Comment by rootulp** [comment]
- [ ] ADR
- [ ] Update reserved namespace shares to use universal share encoding
- [ ] Update non-reserved namespace shares to use universal share encoding
- [ ] Write README in share pkg that describes universal share encoding
- [ ] Update specs

**Comment by evan-forbes** [comment]
I like that idea. our whole naming scheme has kinda been thrown off since we changed `PayForMessage` to `PayForData` (which was a really good change imo). Might just want to refactor the `Message` struct to `ShareData` or something and stick everything in that.

**Comment by rootulp** [comment]
I've been confused on this because I've been using `Message` for message shares and did not think that term applied to shares in the reserved namespace (i.e. transactions, ISRs, evidence).  See https://github.com/celestiaorg/celestia-app/pull/660#discussion_r957457800

If we've been using `Message` to also describe data in reserved namespaces, I totally agree with your suggestion and will create an issue for it.
