### ISSUE TITLE
Mamaki Upgade Tracking Issue

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#663]
Here's a tracking issue for the next mamaki upgrade. We want to fit in as many consensus breaking changes at once. 

- [x] https://github.com/celestiaorg/celestia-app/pull/472
- [x] https://github.com/celestiaorg/celestia-app/pull/618
- [x] https://github.com/celestiaorg/celestia-app/pull/607
- [x] https://github.com/celestiaorg/celestia-app/issues/382 (<- implemented but not reviewed)
- [x] https://github.com/celestiaorg/celestia-app/issues/608 (<- needs investigation)
- [x] https://github.com/celestiaorg/celestia-app/issues/770
