### ISSUE TITLE
Parameter picking Tracking issue

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#669]
We need to do a lot of investigation based work in order to ensure that we pick correct parameters. This will involve individuals selecting specific sets of parameters, doing some investigation, including performing preliminary network tests, and summarizing this work for comment on other teams. Our goal is to have an official list of parameters decided on by the end of onsite, where we will discuss the params and their respective investigations synchronously.

- [ ] https://github.com/celestiaorg/celestia-app/issues/658
- [ ] https://github.com/celestiaorg/celestia-app/issues/591
- [ ] https://github.com/celestiaorg/celestia-app/issues/590
- [ ] https://github.com/celestiaorg/celestia-app/issues/589

**Comment by evan-forbes** [comment]
In our giant param call, we came to a few decisions that we can track here as well.

## Mempool Config Defaults

- Decided
    - We’re planning on using v1 (prioritized by fee) as a default
    - Its up to validators to modify PrepareProposal to incorporate further ordering
    - Implement a blocklist for the mempool reactor
    - Change the default of the max transaction size accepted to something closer to the max block size
- Undecided
    - default minimum fee in app.toml

## RPC Config

- Decided
    - change the default broadcast-timeout-commit to something roughly double the suspected block time
    - Increase the default max body bytes

## Genesis Params

- Consensus
    - Decided
        - We are not going to use TimeIotaMs to regulate the block time during consensus
        - We have to manually calculate the values for Evidence (time per year / number of blocks per year
- Auth
    - Decided
        - We are leaving the default auth ante handler costs as the default
            - 590 gas per sig
            - 10 Gas per byte for each tx
    - Undecided
        - We might want to decrease the max memo size
- Distribution
    - Decided
        - we will leave WithdrawAddrEnabled
    - Undecided
        - Exact values for community tax, base proposer, and bonus proposer reward
- Mint
    - Decided
        - we want a lower value for inflation
        - we want to set inflation max and inflation min to the same value
    - Undecided
        - the exact values for inflation are tbd
    - Todo
        - lookup what annual provisions are
- Slashing
    - Decided
        - signed blocks window will be increased to roughly a day
    - Undecided
        - exact percentage from slash fraction
- Staking
    - Decided
        - set the min commission to 5%
    - Undecided
        - The exact value to unbonding time: currently 21 days

## Gas

- Decided
    - We still need a more comprehensive examination of the resource pricing
        - We will create a deliverable to document the exact gas used and how its calculated for standard txs in the specs
    - We will add two new constants for gas consumed by PFDs
        - Base gas
        - per byte multiplier
        - We want to increase the initial per byte gas cost to 8 and base cost to 0

**Comment by evan-forbes** [comment]
we should also fix https://github.com/celestiaorg/cosmos-sdk/issues/283

before closing this issue

**Comment by evan-forbes** [comment]
can close since all parameters have been chosen
