### ISSUE TITLE
specs: consensus leader selection & fork choice

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#735]
## Summary 

Currently, the specs do not define the concrete Leader selection and the Fork Choice rule:
https://github.com/celestiaorg/celestia-specs/blob/06be92043f8ec39bab4222708c0fb44eb7fbca60/src/specs/consensus.md#fork-choice

IMO, these could be very short paragraphs (one or two sentences) that give an overview and refer to tendermint for the details. If there is anything LL specific to consider here (e.g. any difference that stems from the minority assumption), it should also be mentioned somewhere.

## Sub-Tasks
We also need to consider:
- [x] timeouts
- [x] data becoming available after the fact 
- [ ] erasure coding fraud proofs
- [x] fork choice with DAS (ref: https://github.com/celestiaorg/lazyledger-core/issues/321, celestiaorg/celestia-specs#179)

partly includes: celestiaorg/celestia-node#1134

**Comment by rootulp** [comment]
Can link to Tendermint docs
