### ISSUE TITLE
Replace usage of `TIA` with `CLS` in downstream repos

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#862]
## Context

After we have a celestia-app release that includes https://github.com/celestiaorg/celestia-app/pull/859 we'll want to upgrade downstream repos and replace usage of `TIA` with `CLS` 

Ref: https://github.com/search?p=1&q=org%3Acelestiaorg+tia&type=Code

## Repos
- [ ] https://github.com/celestiaorg/arabica-devnet
- [ ] https://github.com/celestiaorg/ephemeral-cluster
- [ ] https://github.com/celestiaorg/devops-test
- [ ] https://github.com/celestiaorg/networks
- [ ] https://github.com/celestiaorg/ethermint-networks
- [ ] https://github.com/celestiaorg/test-infra

**Comment by SweeXordious** [comment]
I think this could be a good first issue, what do you think? 
I guess it's not a big change, however, it will familiarize the contributor with the different repos and how they're connected.

**Comment by rootulp** [comment]
Closing this b/c we reverted from CLS back to TIA.
