### ISSUE TITLE
[EPIC] QGB Before incentivized testnet tasks tracker

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#952]
We will need to finish the following tasks before incentivized testnet:

- [x] https://github.com/celestiaorg/celestia-app/issues/953
- [x] https://github.com/celestiaorg/celestia-app/issues/954
- [x] https://github.com/celestiaorg/celestia-app/issues/956
